name: Build Android APK
on: [push] # This builds the app every time you save/push code

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          
      - name: Build Child App
        run: |
          cd flutter_child_app
          flutter pub get
          flutter build apk --release
          
      - name: Build Parent App
        run: |
          cd flutter_parent_app
          flutter pub get
          flutter build apk --release

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: app-apks
          path: |
            flutter_child_app/build/app/outputs/flutter-apk/app-release.apk
            flutter_parent_app/build/app/outputs/flutter-apk/app-release.apk
